# DO NOT EDIT This file was generated from a template, please edit qubes-mgmt-salt-user-qvm-features-in-pillar.spec.tmpl instead.

Name:           qubes-mgmt-salt-user-qvm-features-in-pillar
Version:        1.0.0
Release:        1%{?dist}
Summary:        A Salt formula that exposes QVM features in Salt pillar

License:        GPLv2
URL:            https://github.com/gonzalo-bulnes/qubes-mgmt-salt-user
Source0:        %{name}-%{version}.tar.gz

Group:          System administration tools
BuildArch:      noarch

%description
A Salt formula that exposes QVM features in Salt pillar.

%prep
%setup -q

%build
make

%install
make install DESTDIR=%{buildroot}

%files
%license LICENSE
%doc README.md CHANGELOG.md
/srv/user_salt/qvm-features-in-pillar

%changelog
* Wed Sep 13 2023 Gonzalo Bulnes Guilpain <gon.bulnes@fastmail.com>
- Initial packaging
